swagger: '2.0'
info:
  title: DCP Query Service API
  description: Data Coordination Platform Query Service API
  version: "0.0.1"
host: ${API_HOST}
schemes:
  - https
basePath: /
consumes:
  - application/json
  - application/octet-stream
produces:
  - application/json

paths:

  /v1/health:
    get:
      summary: Retreive health status of Query Service
      description: |
        Returns a 200 if Query Service is healthy.
      operationId: query.lambdas.api_server.v1.endpoints.health
      tags:
        - All
      responses:
        200:
          description: Status is nominnal.
        503:
          description: Service unavailable.
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /v1/query:
    post:
      summary: Fast completing user written query of hca metadata
      description: Query the database (query must complete within API gateway's 30 second timeout)
      operationId: query.lambdas.api_server.v1.endpoints.query
      tags:
        - All
      parameters:
        - name: query_string
          in: body
          schema:
            type: string
      responses:
        200:
          description: Query received and processed
          schema:
            type: object
            properties:
              query:
                type: string
                description: Submitted query
              results:
                type: array
                description: Results of query
                items:
                  type: object
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /v1/webhook:
    post:
      summary: Endpoint for DSS subscription
      description: |
        Recieves a subscription event from the DSS containing the id and version of a bundle that has been added. Extracts the metadata attached to that bundle, transforms it and loads it into the db.
      operationId: query.lambdas.api_server.v1.endpoints.webhook
      tags:
        - All
      parameters:
        - name: subscription_data
          in: body
          schema:
            $ref: '#/definitions/SubscriptionData'
      responses:
        202:
          description: Data accepted for processing
          schema:
            type: object
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:

  Error:
    type: object
    properties:
      status:
        type: integer
        format: int32
        description: HTTP error code.
      title:
        type: string
        description: Human-readable error message.
      detail:
        type: string
        description: Exception stacktrace, if any.
    required:
      - status
      - title


  SubscriptionData:
    type: object
    properties:
      match:
        type: object
        properties:
          bundle_uuid:
            type: string
          bundle_version:
            type: string